// Model for widgetLayouts collection

// Imports
const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const counterModel = require('./counters')

// Schema
const WidgetLayoutSchema = new Schema({
    id: Number,                             // Unique ID
    dashboardLayoutID: Number,              // FK of the D Layout to which it belongs
    height: Number,                         // Heigth of box
    left: Number,                           // Left position
    top: Number,                            // Top position
    width: Number,                          // Width of box

    // Generated by the system
    editedBy: String,                       // Last user who edited this task
    editedOn: Date,                         // Date this task was last edited
    createdBy: String,                      // UserID who created this task, can be System
    createdOn: {                            // Date task was created
        type: Date,
        // `Date.now()` returns the current unix timestamp as a Number,        default: Date.now
    }

});

// This pre-hook is called before the information is saved into the database
WidgetLayoutSchema.pre('save', function(next) {
    var doc = this;

    // Find in the counters collection, increment and update
    counterModel.findOneAndUpdate(
        {_id: 'widgetLayouts.id'},
        {$inc: { seq: 1} },
        { upsert: true, new: true },
        function(error, counter)   {
            if(error) {
                return next(error);
            };

            doc.id = counter.seq;
            next();
        }
    );
});

// Create Model: modelName, schema, collection
const WidgetLayoutModel = mongoose.model(
    'widgetLayouts', 
    WidgetLayoutSchema, 
    'widgetLayouts'
);

// Export
module.exports = WidgetLayoutModel;