###

POST http://localhost:8000/auth/local/signup -H "application/json" -d 'password=jannie' -d 'email=jannie@gmail.com'
###

POST http://localhost:8000/auth/local/login -H "application/json" -d 'password=jannie' -d 'email=jannie@gmail.com'
###

GET http://localhost:8000/loginLocal

###

GET http://localhost:8000/auth/local/verify?userID=JannieI

###
POST http://localhost:8000/auth/local/verify -H "application/json" -d 'userID=JannieI'

###