// File Variables
@host = http://localhost:8000
###


// Signup
POST {{host}}/auth/local/signup
content-type: application/json 

{
    "companyName": "Clarity Analytics",
    "userID": "JannieI",
    "password": "xxx" 
} 
###


// Local Login
POST {{host}}/auth/local/login
content-type: application/json

{
    "companyName": "Clarity Analytics",
    "userID": "JannieI",
    "password": "123" 
}
###


// Verify
POST {{host}}/auth/local/verify
content-type: application/json

{
    "userID": "JannieI"
}
###


// Users
GET {{host}}/users
###


// ....
POST {{host}}/

###


// Local Profile
GET {{host}}/auth/local/profile?secret_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiX2lkIjoiNWMxNWY4ODVmYmE4ZDQ3ZjY3YzI5NTEzIiwidXNlcklEIjoiSmFubmllSSIsImlhdCI6MTU0NTEyMDk2OSwiZXhwIjoxNTQ1MjA3MzY5fQ.1QRX0PNJjWT_QYd7IrEe7FbpbpYODUqD4-s7KnvR7Qc

###


// Canvas Data
GET {{host}}/canvasdata/:tests?companyName=Ryan

###
