@host = http://localhost:8000

###

POST http://localhost:8000/auth/local/signup -H "application/json" -d 'password=jannie' -d 'email=jannie@gmail.com'
###

POST http://localhost:8000/auth/local/login -H "application/json" -d 'password=jannie' -d 'email=jannie@gmail.com'
###

GET http://localhost:8000/loginLocal

###

GET {{host}}/auth/local/verify?userID=JannieI

###
POST {{host}}/auth/local/verify
content-type: application/json

{
    "userID": "JannieI"
}

###

GET http://localhost:8000/users

###

POST http://localhost:8000/

###