// Model for DashboardScheduleLogs collection

// Imports
const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const counterModel = require('./counters')

// Schema
const DashboardScheduleLogSchema = new Schema({
    id: Number,                             // Unique ID
    dashboardID: Number,                    // D that was linked
    userID: String,                         // User to whom D was sent
    groupID: String,                        // Optional Group to which D was sent
    sentOn: Date,                           // Date dispatched
    status: String,                         // Pending, Halted, Success, Failed
    errorMessage: String,                   // Error message if it failed

    // Generated by the system
    editedBy: String,                       // Last user who edited this task
    editedOn: Date,                         // Date this task was last edited
    createdBy: String,                      // UserID who created this task, can be System
    createdOn: {                            // Date task was created
        type: Date,
        // `Date.now()` returns the current unix timestamp as a Number,        default: Date.now
    }
});

// This pre-hook is called before the information is saved into the database
DashboardScheduleLogSchema.pre('save', function(next) {
    var doc = this;

    // Find in the counters collection, increment and update
    counterModel.findOneAndUpdate(
        {_id: 'dashboardScheduleLog.id'},
        {$inc: { seq: 1} },
        { upsert: true, new: true },
        function(error, counter)   {
            if(error) {
                return next(error);
            };

            doc.id = counter.seq;
            next();
        }
    );
});

// Create Model: modelName, schema, collection
const DashboardScheduleLogModel = mongoose.model('dashboardScheduleLog', DashboardScheduleLogSchema, 'dashboardScheduleLog');

// Export
module.exports = DashboardScheduleLogModel;