// Model for dashboardTabs collection

// Imports
const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const counterModel = require('./counters')

// Schema
const DashboardTabSchema = new Schema({
    id: Number,                             // Unique record ID
    originalID: Number,                     // Optional T-id from which this T was copied
    dashboardID: Number,                    // FK to DashboardID to which widget belongs
    name: String,                           // Short Name
    description: String,                    // Description
    displayOrder: Number,                   // Sort on this to order tabs on D
    backgroundColor: String,                // Bg Color of T on Status Bar
    backgroundColorName: String,            // Name of Bg Color of T on Status Bar
    color: String,                          // Color of T name on Status Bar
    colorName: String,                      // Name of Color of T name on Status Bar

    // Generated by the system
    editedBy: String,                       // Last user who edited this task
    editedOn: Date,                         // Date this task was last edited
    createdBy: String,                      // UserID who created this task, can be System
    createdOn: {                            // Date task was created
        type: Date,
        // `Date.now()` returns the current unix timestamp as a Number,        default: Date.now
    }
});

// This pre-hook is called before the information is saved into the database
DashboardTabSchema.pre('save', function(next) {
    var doc = this;

    // Find in the counters collection, increment and update
    counterModel.findOneAndUpdate(
        {_id: 'dashboardTabs.id'},
        {$inc: { seq: 1} },
        { upsert: true, new: true },
        function(error, counter)   {
            if(error) {
                return next(error);
            };

            doc.id = counter.seq;
            next();
        }
    );
});

// Create Model: modelName, schema, collection
const DashboardTabModel = mongoose.model('dashboardTabs', DashboardTabSchema, 'dashboardTabs');

// Export
module.exports = DashboardTabModel;