// Model for dashboardSubscriptions collection

// Imports
const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const counterModel = require('./counters.model')

// Schema
const DashboardSubscriptionSchema = new Schema({
    id: Number,                             // Unique ID
    dashboardID: Number,                    // FK to Dashboard
    userID: String,                         // User
    view: Boolean,                          // Nofity if another user Views this D
    editmode: Boolean,                      // Nofity if another user goes to EditMode on this D
    saved: Boolean,                         // Nofity if another user Saved this D
    deleted: Boolean,                       // Nofity if another user Deleted this D
    dashboardCode: String,                  // D-Code filled in at Runtime
    notify: String,                         // How to be notified: Email, Message, Both

    // Generated by the system
    editedBy: String,                       // Last user who edited this task
    editedOn: Date,                         // Date this task was last edited
    createdBy: String,                      // UserID who created this task, can be System
    createdOn: {                            // Date task was created
        type: Date,
        // `Date.now()` returns the current unix timestamp as a Number,        default: Date.now
    }
});

// This pre-hook is called before the information is saved into the database
DashboardSubscriptionSchema.pre('save', function(next) {
    var doc = this;

    // Find in the counters collection, increment and update
    counterModel.findOneAndUpdate(
        {_id: 'dashboardSubscriptions.id'},
        {$inc: { seq: 1} },
        { upsert: true, new: true },
        function(error, counter)   {
            if(error) {
                return next(error);
            };

            doc.id = counter.seq;
            next();
        }
    );
});

// Create Model: modelName, schema, collection
const DashboardSubscriptionModel = mongoose.model(
    'dashboardSubscriptions', 
    DashboardSubscriptionSchema, 
    'dashboardSubscriptions'
);

// Export
module.exports = DashboardSubscriptionModel;